Add Judgement per Lane
Quaver/Quaver pull request #3596
Opened 2022-08-14 22:49 UTC by Kizuna-dev

Closes https://github.com/Quaver/Quaver/issues/2674

New skin.ini features : 
- **DisplayJudgementsInEachColumn**
    - As the name indicate, instead of one judgement in the middle, now there is a judgement for each lane, centered on each of them
- **RotateJudgements**
    - Only work if DisplayJudgementsInEachColumn is true. Rotate the judgement based on the lane it is

https://user-images.githubusercontent.com/68703144/184557660-8d40a290-4f97-41dd-9314-490b27ce2dbf.mp4

2022-08-24 21:14 UTC, IceDynamix requested changes

2022-08-24 21:14 UTC, IceDynamix commented on Quaver.Shared/Screens/Gameplay/Rulesets/Input/InputManagerKeys.cs
> +                playfield.Stage.JudgementHitBurst[Math.Clamp(lane, 0, playfield.Stage.JudgementHitBurst.Count - 1)].PerformJudgementAnimation(judgement);
Make a variable for `Math.Clamp(lane, 0, playfield.Stage.JudgementHitBurst.Count - 1)` because it's repeated very often

2022-08-24 21:14 UTC, IceDynamix commented on Quaver.Shared/Screens/Gameplay/Rulesets/Keys/Playfield/GameplayPlayfieldKeysStage.cs
> +        public List<JudgementHitBurst> JudgementHitBurst { get; private set; }
Rename to `JudgementHitBursts`, plural for lists

2022-08-24 21:14 UTC, IceDynamix commented on Quaver.Shared/Screens/Gameplay/Rulesets/Keys/Playfield/GameplayPlayfieldKeysStage.cs
> +            var judgementBurstCount = skin.DisplayJudgementsInEachColumn == true ? Screen.Map.GetKeyCount(Screen.Map.HasScratchKey) : 1;
```suggestion
            var judgementBurstCount = skin.DisplayJudgementsInEachColumn ? Screen.Map.GetKeyCount(Screen.Map.HasScratchKey) : 1;
```

2022-08-24 21:14 UTC, IceDynamix commented on Quaver.Shared/Screens/Gameplay/Rulesets/Keys/Playfield/GameplayPlayfieldKeysStage.cs
> +                    X = skin.DisplayJudgementsInEachColumn == true ? Receptors[i].X - ((Playfield.Width / 2) - (Playfield.LaneSize / 2)) : 0
Remove `== true` and extract `Playfield.Width / 2) - (Playfield.LaneSize / 2)` as a variable

2022-08-24 21:14 UTC, IceDynamix commented on Quaver.Shared/Screens/Gameplay/Rulesets/Keys/Playfield/GameplayPlayfieldKeysStage.cs
> +            for (var i = 0; i < judgementBurstCount; i++)
Rename `i` to `lane` for clarification

2022-08-24 21:36 UTC, Kizuna-dev commented
Applied all change

2022-08-25 22:53 UTC, IceDynamix requested changes
Fix codefactor issue

2022-10-30 19:10 UTC, Swan approved these changes

2022-10-30 19:11 UTC, merged