Add settings to change the map selected by default for a mapset
Quaver/Quaver pull request #3676
Opened 2022-10-28 02:13 UTC by Illuminati-CRAZ

Resolves #2082

Instead of selecting the first map in a mapset, the game can now select a map the is closest to/at least/at most some difficulty. Can also prioritize selecting between 4k and 7k in a multimode mapset. The default settings should result in the same map selection behavior as now.

Changed pretty much every seemingly relevant instance of selecting a map, such as `MapManager.Selected.Value = mapset.Maps.First()`, to `MapManager.SelectMapInMapset(mapset)`

Also updated the C# language version of Quaver.Shared to the latest (C#10) and the launch.json file for vscode debugging.

2022-10-30 18:56 UTC, Swan commented
How about instead of doing this, we use the player's local/online rating to get the approximate difficulty they should play, and set the map based on that? 

Just seems a lot simpler than having the user set two more options (adding complexity) for arguably the same result.

2022-10-30 19:04 UTC, Illuminati-CRAZ commented
I guess you're right, but imo I would leave the target difficulty in case they either don't like the auto determined difficulty (or just wanna auto-select the lowest or highest diff), and I think the gamemode prioritization would be nice for most people who mainly play one keymode.

2022-10-30 19:36 UTC, Swan commented
Both are fine with me. Target difficulty should just be an override of the default behavior

2023-01-09 23:09 UTC, Illuminati-CRAZ commented
DIfficulty suggester isn't tested, can't test with online profile, but the code was modelled off of the difficulty suggester on download screen. Ideally it would use the local profile when offline, but idk how to access the local stats.

2023-01-10 10:42 UTC, IceDynamix commented
You can check how the F4 profile in the song selection initializes the different profiles for the table here https://github.com/Quaver/Quaver/blob/ui-redesign/Quaver.Shared/Screens/Selection/UI/Profile/ProfileSelectionDropdown.cs

2023-01-10 19:34 UTC, Swan requested changes

2023-01-10 19:34 UTC, Swan commented on Quaver.Shared/Screens/Options/Items/Custom/OptionsItemSuggestDifficulty.cs
> +                ConfigManager.PrioritizedMapDifficulty7K.Value = (int)(diff * 10);
Try using [UserProfileDatabaseCache.Selected](https://github.com/Quaver/Quaver/blob/7ac14c2c6526a4bd89be01e28412a2e591aa7e11/Quaver.Shared/Database/Profiles/UserProfileDatabaseCache.cs) instead?

2023-01-10 23:04 UTC, IceDynamix commented on Quaver.Shared/Quaver.Shared.csproj
> +  </PropertyGroup>
Agree. If anything, this should be discussed and implemented in a separate issue/PR.

2023-01-14 22:01 UTC, Illuminati-CRAZ commented on Quaver.Shared/Quaver.Shared.csproj
> +  </PropertyGroup>
Will revert, it looks like there could also potentially be incompatibilities with the target framework that I didn't consider

2023-01-15 15:30 UTC, Swan approved these changes

2023-01-15 15:30 UTC, merged