Create base keybind config system
Quaver/Quaver pull request #3688
Opened 2022-11-11 03:02 UTC by IceDynamix

Keybind config that can parse to and from yaml

2022-11-23 20:51 UTC, AiAe requested changes
The config file is only created when entering Editor.
Unsure if this was the intended fix but having saved just "Ctrl+" its getting replaced by "Ctrl+None", probably better to just default it to None?

The keybinds needs to be more prone to bad syntax, for example if I do "[None] +" or "[None" editor wont load anymore.

2022-12-04 16:46 UTC, Swan requested changes

2022-12-04 16:46 UTC, Swan commented on Quaver.Shared/Screens/Edit/Input/EditorInputConfig.cs
> +        }
If this fails, the game will crash. In some cases you're handling it with a try/catch but in other cases you aren't. It either needs to be handled once here (ideally), or handled in each individual use case.

2022-12-04 16:46 UTC, Swan commented on Quaver.Shared/Screens/Edit/Input/EditorInputConfig.cs
> +            return config;
```suggestion
            if (!File.Exists(ConfigPath))
            {
                Logger.Debug("No editor key config found, using default", LogType.Runtime);
                config.SaveToConfig();
                return config;
            }

            try
            {
                using (var file = File.OpenText(ConfigPath))
                    config = Deserialize(file);

                Logger.Debug("Loaded editor key config", LogType.Runtime);
                config.SaveToConfig(); // Reformat after loading
            }
            catch (Exception e)
            {
                Logger.Error($"Could not load editor key config, using default: {e.Message}", LogType.Runtime);
            }

            return config;
```

Just to reduce nesting a bit.

2022-12-04 16:46 UTC, Swan commented on Quaver.Shared/Screens/Edit/Input/EditorInputConfig.cs
> +                throw new Exception($"Failed to parse configuration in line {e.Start.Line}");
Kinda defeats the purpose of the try catch if it's going to throw another exception? Maybe just return a fresh instance of the config and log the error.

2022-12-04 16:46 UTC, Swan commented on Quaver.Shared/Screens/Edit/Input/EditorInputManager.cs
> +        private void HandleKeypresses()
```suggestion
        private void HandleKeyPresses()
```

And all other instances of Presses not being capitalized.

2022-12-04 16:46 UTC, Swan commented on Quaver.Shared/Screens/Edit/Input/EditorInputConfig.cs
> +                Logger.Debug(e.ToString(), LogType.Runtime);
Log it as an error.

2022-12-04 16:46 UTC, Swan commented on Quaver.Shared/Screens/Edit/Input/KeybindActions.cs
> +        DebugAction
You can remove this action before this gets merged.

2022-12-04 17:54 UTC, AiAe commented
Writing the issues from our DMs:
Alert needs to be added for when it fails to parse/load the keybinds.
If the file is left empty the editor will still not open.

```
[9:00:54] - RUNTIME - ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Screens.Edit.Input.EditorInputManager..ctor(EditScreen screen) in C:\Users\AiAe\Downloads\Quaver\Quaver.Shared\Screens\Edit\Input\EditorInputManager.cs:line 44
   at Quaver.Shared.Screens.Edit.EditScreen..ctor(Map map, IAudioTrack track, EditorVisualTestBackground visualTestBackground) in C:\Users\AiAe\Downloads\Quaver\Quaver.Shared\Screens\Edit\EditScreen.cs:line 289
   at Quaver.Shared.Screens.Selection.SelectionScreen.<>c__DisplayClass69_0.<ExitToEditor>b__0() in C:\Users\AiAe\Downloads\Quaver\Quaver.Shared\Screens\Selection\SelectionScreen.cs:line 714
   at Quaver.Shared.Screens.QuaverScreenManager.<>c__DisplayClass24_0.<ScheduleScreenChange>b__0() in C:\Users\AiAe\Downloads\Quaver\Quaver.Shared\Screens\QuaverScreenManager.cs:line 205
   at Quaver.Shared.Scheduling.ThreadScheduler.<>c__DisplayClass1_0.<Run>b__0() in C:\Users\AiAe\Downloads\Quaver\Quaver.Shared\Scheduling\ThreadScheduler.cs:line 38
```

2022-12-07 20:44 UTC, Swan requested changes

2022-12-07 20:44 UTC, Swan commented on Quaver.Shared/Screens/Edit/Input/EditorInputConfig.cs
> +                throw new Exception("Config file is empty");
This should recreate the config file for them instead of throwing an exception.

2022-12-09 03:09 UTC, merged