Ghost lobby fix
Quaver/Quaver pull request #3866
Opened 2023-08-16 15:03 UTC by WarpABoi

most likely fixes the issue, tho im unable to test multiplayer stuff.

fixes #3865

2023-08-16 22:55 UTC, Swan requested changes
This is an odd way of doing this.

To solve the issue listed, simply prevent the user from going to that screen if they're in a multiplayer game rather than leaving the game entirely.

2023-08-17 06:48 UTC, WarpABoi commented
when in the multiplayer screen it allows you to exit with the home button in the header.

wouldnt it be inconsistent to restrict it in the song select?

2023-08-17 14:37 UTC, Swan commented
The elegant solution would be to leave the game when the user clicks on the home button.

2023-08-18 13:32 UTC, Swan approved these changes

2023-08-18 13:32 UTC, merged