Unify scrolling and add option for inverted scrolling
Quaver/Quaver pull request #3971
Opened 2024-03-03 16:47 UTC by QiuFeng54321

Closes #3970

2024-03-16 15:26 UTC, QiuFeng54321 commented
Here is a video of it working (you can see how I'm physically scrolling the mouse through the overlay at the left):


https://github.com/Quaver/Quaver/assets/32996262/4d439039-3eaa-4354-9c52-57fdd31232f6

2024-04-08 20:49 UTC, Warp9000 requested changes

2024-04-08 20:49 UTC, Warp9000 commented on Quaver.Shared/Screens/Options/OptionsMenu.cs
> +                        new OptionsItemCheckbox(containerRect, "Invert Scrolling", ConfigManager.InvertScrolling)
Move this to Misc section.

2024-04-08 20:49 UTC, Warp9000 commented on Quaver.Shared/Screens/Settings/SettingsDialog.cs
> +                    new SettingsBool(this, "Editor - Invert Scrolling", ConfigManager.InvertScrolling)
This is the old settings screen, it will be removed soon.

2024-04-09 09:08 UTC, Warp9000 approved these changes

2024-04-09 09:08 UTC, merged