Migrate to .NET 8
Quaver/Quaver pull request #3982
Opened 2024-03-20 13:47 UTC by Emik03

This pull request migrates the project to .NET 8, making the same change of swapping `BinaryFormatter` with `XmlSerializer` in a copy of the function. (see https://github.com/Quaver/Quaver.API/pull/153)

Compiled successfully and ran without issues on Linux. Performance should theoretically be improved, but I haven't noticed so far.

2024-03-23 19:11 UTC, AiAe commented
The github workflow also needs to be updated to test for it. https://github.com/Quaver/Quaver/blob/ui-redesign/.github/workflows/dotnet.yml#L22

2024-03-25 22:11 UTC, Illuminati-CRAZ commented
> Performance should theoretically be improved, but I haven't noticed so far.

My assumption is that the .NET 8 performance improvements affect CPU, but it's the GPU that bottlenecks performance for Quaver.

2024-03-25 23:32 UTC, Illuminati-CRAZ requested changes
Could you have Quaver.Shared target .net8 and Quaver.API target .net6 (for Quaver.API this should be as simple as updating the submodule to use the master branch)

2024-03-25 23:32 UTC, Illuminati-CRAZ commented on Quaver/Quaver.csproj
> +    <OutputType>Exe</OutputType>
Not sure why the output type is being changed. By changing it from WinExe to Exe a console window is showing up on game startup.

2024-04-09 11:07 UTC, AiAe commented
Will close this PR for now since it also has breaking change

2024-04-09 11:07 UTC, closed without merging