Improve mapset download
Quaver/Quaver pull request #4118
Opened 2024-05-11 07:29 UTC by QiuFeng54321

**Requires** https://github.com/Quaver/Quaver.Server.Client/pull/16 and https://github.com/Quaver/Quaver.Resources/pull/16

Adds the ability to pause/resume, stop, retry and remove downloads.

It looks like this:
![image](https://github.com/Quaver/Quaver/assets/32996262/b0185aa1-9802-419a-a570-0c61052c7f58)

2024-10-24 19:13 UTC, WilliamQiufeng commented
Should be ready for review

2024-10-25 15:15 UTC, Swan requested changes
The download progress seems to break with this. When clicking on a mapset it goes from 0% to 100%, then stays there until it completes.

https://streamable.com/qoxoue

2024-10-27 20:03 UTC, WilliamQiufeng commented
> The download progress seems to break with this. When clicking on a mapset it goes from 0% to 100%, then stays there until it completes.
> 
> https://streamable.com/qoxoue

It seems like it is due to HEAD requests not being allowed in api-v2. AiAe has made relevant change for that (https://github.com/Quaver/api-v2/pull/119). Please check if it works.

2024-10-28 13:22 UTC, Swan approved these changes

2024-10-28 13:22 UTC, merged