Add a search filter for scroll velocity changes
Quaver/Quaver pull request #4125
Opened 2024-05-14 20:23 UTC by faluhub

This pr adds a search filter for the amount of slider velocity changes in a map. Its short name is `svc`. Must refresh beatmaps before results show up :)

2024-05-16 15:53 UTC, AiAe commented
I think this needs to be improved to ignore scroll velocities at 1.00x, because they are marked falsely as scroll velocity. 
For example this map will show when searching for svc>0 https://quavergame.com/mapset/map/16

2024-05-16 18:29 UTC, Emik03 commented
Wouldn't this also include osu! normalization SVs, so you can't just say "ignore 1x", it must be "ignore *perceived* 1x-ish". (rounded due to floating points)

2024-05-17 03:27 UTC, Illuminati-CRAZ commented
Clearly we should implement an SV difficulty calculator for this

2024-05-17 03:34 UTC, Illuminati-CRAZ commented
On a serious note, I personally don't think we should add scroll velocity _count_ as a thing to filter by. A bunch of "normal" maps will be would be filtered out by "svc = 0" because they use SVs for BPM normalization, and at higher sv counts it stops being a good metric for distinguishing between SV maps.

2024-05-18 17:16 UTC, AiAe requested changes
Read PR comments

2024-07-10 18:01 UTC, closed without merging