Allow placing long notes during livemapping
Quaver/Quaver pull request #4221
Opened 2024-07-15 08:26 UTC by WilliamQiufeng

Resolves #4220

Adds two menu options: a toggle for placing long notes during livemapping (defaults to true), and a setting for the minimum threshold to hold the key to recognize it as a long note (defaults to 100ms).

2024-07-15 16:33 UTC, AiAe commented
The issue also mentions they want to rebind the default key binds for live mapping from 1 2 3 4. 
This PR does not fully resolve the issue. 
Is this planned for another PR?

2024-07-15 16:41 UTC, WilliamQiufeng commented
> Is this planned for another PR?

It is. I am thinking about moving them altogether to the new editor input manager

2024-07-15 16:42 UTC, AiAe commented
> > Is this planned for another PR?
> 
> It is. I am thinking about moving them altogether to the new editor input manager

I see, I assume you will have to open/fork Ice's old PR to implement his idea/vision?

2024-07-15 16:47 UTC, WilliamQiufeng commented
> I see, I assume you will have to open/fork Ice's old PR to implement his idea/vision?

I think so. If thngs haven't changed much, I want to continue it from where it was left off some time. BTW I'm also hoping to move the config file to that structured config I added for editor window saving.

2024-07-31 12:37 UTC, Warp9000 requested changes

2024-07-31 12:37 UTC, Warp9000 commented on Quaver.Shared/Screens/Edit/EditScreen.cs
> -
this empty line should stay

2024-07-31 12:37 UTC, Warp9000 commented on Quaver.Shared/Screens/Edit/Dialogs/EditorSetLiveMapLongNoteThresholdDialog.cs
> +                AllowedCharacters = new Regex(@"^[0-9-]*$")
this regex should probably be `^[0-9]*$`

2024-07-31 12:37 UTC, Warp9000 commented on Quaver.Shared/Screens/Edit/Dialogs/EditorSetLiveMapLongNoteThresholdDialog.cs
> +            }
TryParse should probably be used instead

2024-08-04 16:36 UTC, Warp9000 approved these changes

2024-08-04 16:36 UTC, merged